name: fleth
description: Lethil Flutter Template

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.3

  # Local lidea package, development only
  lidea:
    path: ../lidea
    # git:
    #   url: git://github.com/laisiangtho/lidea.git
    #   ref: main

  # Custom
  in_app_purchase: ^1.0.9
  just_audio: ^0.9.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  # Add assets
  assets:
    - assets/env.json
    - assets/album.json

  # Add fonts from package
  fonts:
    - family: Lato
      fonts:
        - asset: packages/lidea/fonts/Lato-Regular.ttf
        - asset: packages/lidea/fonts/Lato-Thin.ttf
        - asset: packages/lidea/fonts/Lato-Light.ttf
        - asset: packages/lidea/fonts/Lato-Bold.ttf

    - family: Lidea
      fonts:
        - asset: packages/lidea/fonts/Lidea.ttf

    - family: Mm3Web
      fonts:
        - asset: packages/lidea/fonts/Mm3Web.ttf

    # - family: Mm3Web
    #   fonts:
    #     - asset: assets/fonts/Mm3Web.ttf
