name: fleth
description: Lethil Flutter Template

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.3

  # Local lidea package, development only
  lidea:
    path: ../lidea
    # git:
    #   url: git://github.com/laisiangtho/lidea.git
    #   ref: main

  # Custom
  hive_flutter: ^1.1.0
  # share: ^2.0.4
  in_app_purchase: ^1.0.8
  just_audio: ^0.9.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/env.json
    - assets/album.json

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Thin.ttf
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-Bold.ttf
    - family: Zaideih
      fonts:
        - asset: assets/fonts/Zaideih.ttf
    # - family: Padauk
      # fonts:
      #   - asset: assets/fonts/Padauk-Regular.ttf
      #   - asset: assets/fonts/Padauk-Bold.ttf
    # - family: Noto Sans Myanmar
    #   fonts:
    #     - asset: assets/fonts/NotoSansMyanmar-Regular.ttf
    #     - asset: assets/fonts/NotoSansMyanmar-Thin.ttf
    #     - asset: assets/fonts/NotoSansMyanmar-Light.ttf
    #     - asset: assets/fonts/NotoSansMyanmar-Bold.ttf

    - family: Mm3Web
      fonts:
        - asset: assets/fonts/Mm3Web.ttf